#!/bin/bash
#set -x

echo $0 $@

[ $# -lt 4 ] && echo "Usage: $0 add|del file_with_routes ip_vpn_partner metric routing_table" && exit 0

# man openvpn:
# cmd tun_dev tun_mtu link_mtu ifconfig_local_ip ifconfig_remote_ip [ init | restart ]
# cmd tap_dev tap_mtu link_mtu ifconfig_local_ip ifconfig_netmask [ init | restart ]
set -x
device=$dev
action="$1"
file="$2"
#ip_remote=$ifconfig_remote
ip_remote=$3
metric="$4"
table="$5"
ip_local=`ip a s $device | fgrep inet | tr -s ' ' | cut -d' ' -f 3 | cut  -d/ -f1`
set +x

set -x
cat $file | while read route; do
    [ -z "$route" ] && continue
    ip route $action $route via $ip_remote dev $device metric $metric
done

ip route show dev $device | while read route; do
    ip route $action $route dev $device table $table
done

ip rule $action from $ip_local lookup $table
set -x

exit 0

